### ISSUE TITLE
Dependencies on AWS instances

### ISSUE THREAD

**Issue by afernandezody** [QMCPACK/qmcpack_workshop_2019#2]
Hi @prckent,
I tried the script in an AWS instance but it's failing (during the PE installation) because of a dependency on f77_zmq (I'm unfamiliar with this package). 
```
configure: Fortran binding of ZeroMQ (f77zmq) is not installed.
QP_ROOT=/home/ubuntu/qp2
configure: Fortran binding of ZeroMQ (f77zmq) is not installed.
Error: build.ninja does not exists.
You need to run ./configure  first.
Cloning into 'qmcpack'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 30 (delta 7), reused 22 (delta 5), pack-reused 0
Unpacking objects: 100% (30/30), done.
/usr/bin/env: ‘python2’: No such file or directory
Error: build.ninja does not exists.
You need to run ./configure  first.
ubuntu@ip-172-31-26-235:~/qp2$ sudo apt-get -y f77zmq
E: Invalid operation f77zmq
```
Not sure if the script is supposed to be run as it is or if it requires some preliminary installations. Thanks.  
P.S. FFTW installation doesn't seem to be included, which might or not be intentional

**Comment by prckent** [comment]
This is trying to install Quantum Package. Unfortunately it seems that there have been incompatible updated since the script was made. QP will need either to be commented out or fixed. It is only needed for workshop tutorials involving QP.

The script very intentionally pulls down Intel MKL which contains an optimized FFTW implementation as well as an Intel CPU optimized BLAS and LAPACK.
